{% set name = "arxiv-collector" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15f4267b075d2a4cdef591ad853a394788f8ff2f9c92422840b328cb07fa31ad

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - arxiv-collector = arxiv_collector:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - arxiv-collector --version
  imports:
    - arxiv_collector

about:
  home: http://github.com/dougalsutherland/arxiv-collector
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A little Python script to collect LaTeX sources for upload to the arXiv'
  description: |
    A small script to collect your LaTeX files for submission to the arXiv. Main features:

    - By default, strips potentially-embarrassing comments from your uploaded
      `.tex` files.
    - Includes the necessary parts of any system package you tell it to upload.
      By default, this includes biblatex (if you use it) to avoid errors like
      `Package biblatex Warning: File '.bbl' is wrong format version`.
    - Only uploads things you actually use: if you have an image you're not
      including anymore or whatever, doesn't upload it.
  dev_url: http://github.com/dougalsutherland/arxiv-collector

extra:
  recipe-maintainers:
    - dougalsutherland
