travis:
  secure:
    BINSTAR_TOKEN: ATNyM/xk5XnRjTgqrisT5J1WH5wWYatDZ/FpZj5zvwUmiRkN8ePGIyztJ2vsFlSwDIbz/nVOKSUef4Gxcu/Hc0UK8wJ4bRx5V050vHf7V981l9/TsPitGYwIRcHjBacbosfqlthdUcLlBnA/wOwXRqeN0SOuM0PbT6dyUssdsquBxL6JLlBehel8SUp8/I6V2ppwJhsnDm9vnHkOq7TuPNOwOoIeLuI4unZjoYeFK4Q4jCNl1ERbNPTFjOOF319lGkOGzyAvpGiJXyOQyrKlbcXtyYHDAbFXaqmwEGS0MPyrlrG5nAhMayNIRXVUvy9UqL4Mp/Ax0cAWCX6VMH/zVosiAoNkOB5kEFOpbUWwmq1A5/X6iEDMXZlF/NwdK1E11B6hAE3pESpleaXmIkbejmikrlQI3drZBq0RD1jSFohG3d8z2K0ASiimHhCxbpCrLnQrQ3inm4VdQxu8J2fwPwQaowE0GLm9/yet+Bxi0IQ8zmgf4P8roOoMOnejjjdvy2dAL+TYSRGy8xO2DFsLJk06Du3rSbP7F/0c5RavqnNpb/R1lwnYeZEpvy+PH/pp7CbPgWi4PnrzhArEzp59w4ZXAZ6qhx41xEnUZN2V/YEkAxAti2Dc5nGMJmUIV5zvq6bkTyn+ZnJ6S+zvxE+QNQJO8hzEd8rmF5OMCLTo9kA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
